### ISSUE TITLE
Get all tweets shown on my account for last 5 minutes

### ISSUE THREAD

**Issue by narikn** [linvi/tweetinvi#1001]
Hi There,

I am following some twitter news accounts like bbc ,cnn. I want to see all tweets posted by them( the accounts which I am following) for the last 5 minutes. Not all but only for last 5 minutes.
Can we do that? If so please please help with sample code.

Thank you,
Sri

**Comment by linvi** [comment]
What you want to use is the HomeTimeline.
You can read more about it here : https://github.com/linvi/tweetinvi/wiki/Timelines

**Comment by narikn** [comment]
I am trying to get all hometime line tweets after every 20 seconds.but GetHomeTimelineAsync is returning null if call more than two times. 
Its working for firstime , but  there after every 20 seconds  call  GetHomeTimelineAsync  returns.

   var startTimeSpan = TimeSpan.Zero;
            var periodTimeSpan = TimeSpan.FromSeconds(20);
            Dictionary<long, string> newsCollection = new Dictionary<long, string>();
            var timer = new System.Threading.Timer((e) =>
            {
              GetTweets(user, newsCollection);
            }, null, startTimeSpan, periodTimeSpan);

Is there any timespan  limit  to call GetTimeHomeLine.

**Comment by linvi** [comment]
There is no TimeSpan.
Please make sure that you are initializing your credentials within the `GetTweets` method.

**Comment by narikn** [comment]
After 6 calls ( 6 *20 seconds)  , GetHomeLine returns null here is the code


`public class TwitterStream
    {
        public static void Main(string[] args)
        {

            var startTimeSpan = TimeSpan.Zero;
            var periodTimeSpan = TimeSpan.FromSeconds(20);
            Dictionary<long, string> newsCollection = new Dictionary<long, string>();

            var timer = new System.Threading.Timer((e) =>
            {
                var test = Auth.SetUserCredentials("xx", "xxx", "xxxx-xxx", "xxxxx");
                var user = User.GetAuthenticatedUser();
                if (user != null)
                {
                    GetTweets2(user, newsCollection);
                }

            }, null, startTimeSpan, periodTimeSpan);

            Console.ReadKey();
        }

        public static void GetTweets2(IAuthenticatedUser user, Dictionary<long, string> newsCollection)
        {
            if (user != null && newsCollection != null)
            {
                var tweetsCollection = user.GetHomeTimelineAsync().Result;
                List<ITweet> validTweets = new List<ITweet>();

                if (tweetsCollection != null)
                {
                    foreach (ITweet item in tweetsCollection.OrderByDescending(x => x.CreatedAt))
                    {
                        TimeSpan timeSpan = DateTime.Now - item.CreatedAt;
                        if (timeSpan.TotalSeconds <= 150)
                        {
                            validTweets.Add(item);
                        }
                    }

                    if (validTweets != null && validTweets.Count() > 0)
                    {
                        newsCollection.Clear();

                        foreach (var item in validTweets.OrderBy(x => x.CreatedAt))
                        {
                            var text = item.Text;
                            var source = item.CreatedBy;

                            var tweetMessage = text.Split(new string[] { "https" }, StringSplitOptions.None);
                            if (tweetMessage.Length > 0)
                            {
                                double timeSpan = Math.Ceiling((DateTime.Now - item.CreatedAt).TotalSeconds);
                                text = tweetMessage[0];
                                if (newsCollection.ContainsKey(item.Id) == false)
                                {
                                    var news = string.Format("{0}--Seconds Ago By: {1}:: {2}", timeSpan, source, text);
                                    newsCollection.Add(item.Id, news);
                                }
                                else
                                {
                                    var updateNews = string.Format("{0}--Seconds Ago By: {1}:: {2}", timeSpan, source, text);
                                    newsCollection[item.Id] = updateNews;
                                }
                            }
                        }
                    }
                    else
                    {
                        if (tweetsCollection != null)
                        {
                            foreach (var oldTweet in tweetsCollection)
                            {
                                foreach (var item in newsCollection)
                                {
                                    if (oldTweet.Id == item.Key)
                                    {
                                        var text = oldTweet.Text;
                                        var source = oldTweet.CreatedBy;
                                        double timeSpan = Math.Ceiling((DateTime.Now - oldTweet.CreatedAt).TotalSeconds);
                                        var tweetMessage = text.Split(new string[] { "https" }, StringSplitOptions.None);
                                        text = tweetMessage[0];
                                        var updateNews = string.Format("{0}--Seconds Ago By: {1}:: {2}", timeSpan, source, text);
                                        newsCollection[item.Key] = updateNews;
                                    }
                                }
                            }
                        }
                    }

                    if (newsCollection != null && newsCollection.Count() > 0)
                    {
                        Console.Clear();
                        int counter = newsCollection.Count();
                        foreach (var item in newsCollection.OrderByDescending(x => x.Key))
                        {
                            Console.WriteLine();
                            var formatedNewsString = string.Format("{0}) {1} ", counter--, item.Value);
                            Console.WriteLine(formatedNewsString);
                        }
                    }
                }
            }

        }
    }`

**Comment by narikn** [comment]
Its just a small console app. You can copy paste and change credentials to test it

**Comment by linvi** [comment]
I would suggest that you disable exception swallowling and send me the error information.

https://github.com/linvi/tweetinvi/wiki/Exception-Handling#per-request-exception-handling

**Comment by narikn** [comment]
I am getting follow error :
1st call looks ok but after few calls I am getting following error,

Erro: {"https://api.twitter.com/1.1/statuses/home_timeline.json?exclude_replies=False&contributor_details=False&count=50&trim_user=False&include_entities=True&tweet_mode=extended web request failed."}
![Error_tweetinvi](https://user-images.githubusercontent.com/8451063/77963781-d60a1c80-7292-11ea-93b1-97633ff71c63.jpg)
![Error_tweetinvi](https://user-images.githubusercontent.com/8451063/77963812-e02c1b00-7292-11ea-8008-60fc9ed37ce9.jpg)

Status Code: 429


Here is the stack strace

   at Tweetinvi.Credentials.TwitterAccessor.HandleQueryException(TwitterException ex)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQueryReturningContent(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Timeline.TimelineController.GetHomeTimeline(IHomeTimelineParameters parameters)
   at Tweetinvi.Logic.AuthenticatedUser.ExecuteAuthenticatedUserOperation[T](Func`1 operation)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Core.Helpers.TaskFactory.<ExecuteTaskAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Logic.AuthenticatedUser.<GetHomeTimelineAsync>d__98.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NewsApp.Program.<GetTweets>d__1.MoveNext() in C:\Users\Kiran\source\repos\NewsApp\NewsApp\Program.cs:line 56

Please find the attachment.
![Error_tweetinvi](https://user-images.githubusercontent.com/8451063/77963867-fdf98000-7292-11ea-94bd-65498054ae8e.jpg)
![Error_tweetinvi](https://user-images.githubusercontent.com/8451063/77963920-110c5000-7293-11ea-8351-d9a3bbe881d9.jpg)

**Comment by linvi** [comment]
You have reached the rate limits. Wait for 15 minutes and you should be back on track.
