### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by Twistere** [linvi/tweetinvi#1054]
Hello, I have a bug with your API. The method ```Tweet.Publish("Exemple")``` doesn't work. This issues not provided by my code because I've tried to use the follow method and it work. I use the version 4.0.3 of your API.

Here my code : 

```csharp
using System;
using Tweetinvi;


namespace _42_piscine_decount
{
    class Program
    {
        static void Main(string[] args)
        {
            var userCredentials = Auth.CreateCredentials(
                "censored",
                "censored",
                "censored",
                "censored"
            );

            var authenticatedUser = User.GetAuthenticatedUser(userCredentials);
            Tweet.PublishTweet("c#");

        }
    }
}
```
And here my error : 
```
otnet run
Unhandled exception. Tweetinvi.Exceptions.TwitterNullCredentialsException: Exception of type 'Tweetinvi.Exceptions.TwitterNullCredentialsException' was thrown.
   at Tweetinvi.WebLogic.TwitterRequestHandler.TryPrepareRequest(IHttpRequestParameters requestParameters, RateLimitTrackerMode rateLimitTrackerMode, ITwitterCredentials credentials, Boolean raiseEvents, ITwitterQuery& twitterQuery)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQueryReturningContent(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecutePOSTQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Tweet.TweetQueryExecutor.PublishTweet(IPublishTweetParameters publishParameters)
   at Tweetinvi.Controllers.Tweet.TweetController.InternalPublishTweet(IPublishTweetParameters parameters)
   at Tweetinvi.Controllers.Tweet.TweetController.PublishTweet(String text, IPublishTweetOptionalParameters optionalParameters)
   at Tweetinvi.Tweet.PublishTweet(String text, IPublishTweetOptionalParameters publishTweetOptionalParameters)
   at _42_piscine_decount.Program.Main(String[] args) in /Users/lucas/Desktop/42-piscine-decount/Program.cs:line 19
```

**Comment by jtrimm007** [comment]
Have you made sure you Twitter API credentials has the appropriate permissions? Login to your app on developer.twitter.com and navigate to this page.

![image](https://user-images.githubusercontent.com/16611773/85286907-7a9a9580-b461-11ea-9b1b-f03af7545d8e.png)

If your app is on read only, it will through this error.

**Comment by linvi** [comment]
@Twistere thanks for reporting this issue.

Please try using the alpha version of Tweetinvi, it contains various fixes including ones about credentials that can be related with this bug.

**Comment by Twistere** [comment]
> @Twistere thanks for reporting this issue.
> 
> Please try using the alpha version of Tweetinvi, it contains various fixes including ones about credentials that can be related with this bug.
> 
> Please let me know if this helps you fixing the issue.

Thanks,  it's work fine 👍
