### ISSUE TITLE
IOException in TwitterStream app (v5.0.3)

### ISSUE THREAD

**Issue by ndsvw** [linvi/tweetinvi#1090]
I was trying to let my TwitterStream application run a longer time (overnight, so my Desktop PC switched into some kind of mode where the network connections are cut) while catching TwitterException and handling it. But there was an IOException I did not expect:

```
System.IO.IOException: The response ended prematurely.
   at Tweetinvi.Streams.StreamTask.RunStreamAsync()
   at Tweetinvi.Streams.StreamTask.StartAsync()
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.StartAsync(Func`2 onJsonReceivedCallback, Func`1 createTwitterRequest)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.StartAsync(Action`1 onJsonReceivedCallback, Func`1 createTwitterRequest)
   at Tweetinvi.Streams.FilteredStream.StartMatchingAnyConditionAsync()
   at TwitterDotNet.LiveHashtagLogger.Run() in /a/b/c/d.cs:line 36
   at TwitterDotNet.Program.Main(String[] args) in /a/b/c/e.cs:line 27
Unhandled exception. System.IO.IOException: The response ended prematurely.
   at Tweetinvi.Streams.StreamTask.RunStreamAsync()
   at Tweetinvi.Streams.StreamTask.StartAsync()
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.StartAsync(Func`2 onJsonReceivedCallback, Func`1 createTwitterRequest)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.StartAsync(Action`1 onJsonReceivedCallback, Func`1 createTwitterRequest)
   at Tweetinvi.Streams.FilteredStream.StartMatchingAnyConditionAsync()
   at a.b.Run() in /a/b/c/d.cs:line 36
   at a.Program.Main(String[] args) in /a/b/c/e.cs:line 27
   at a.Program.<Main>(String[] args)
```

Version Used:
5.0.3

**Comment by linvi** [comment]
Sorry for very late response. I will mark this as a bug and try to get a fix out.

**Comment by linvi** [comment]
Thank you for that. This is not actually a bug. 
I will update the documentation to reflect this.

**Comment by Scobiform** [comment]
Yes, it is - thx for posting. Was researching this and an uncaught AuthException right now.

**Comment by ertan2002** [comment]
I have the same exception but I have an idea that may be help to solve the problem.

I have two webservices and one webservice is working on a domain name, and another is working on localhost on the same server. The global webservice calls some methods or an event is triggered from the localhost webservice. 

After a call, exactly after 5 minutes later I get this exception and my app is shutting down.

Example 1:
after 5 minutes, this event is triggered
            _streamV2.EventReceived += _streamV2_EventReceived;

https://i.imgur.com/x61yVd5.png

Example 2:

I call a method in my global API and the global API call a method in localhost API that is SearchTwitterUser. I get the result no problem but after 5 minutes later, the app is shutting down..

PS: this log is from localhost API.

https://i.imgur.com/lclwbxX.png

My conclusion: when a request comes or an event is triggered, somehow it affects Stream Listener task and an exception occurs..

Hope it helps and you solve it as soon as possible :)) 

Thank you

**Comment by xPaw** [comment]
Are you sure it's not a bug when it throws in `StreamResultGenerator.StartAsync` which doesn't go through `StreamStopped`?

It would be nice if docs had a correct example of how to handle disconnections/exceptions so you can have reliable stream.

**Comment by dkonyayev** [comment]
I also experienced this today. I saw in the post previously that documentation will be updated about this but I did not find anything. Running version 5.0.4

System.IO.IOException
  HResult=0x80131620
  Message=The response ended prematurely.
  Source=Tweetinvi.Streams
  StackTrace:
   at Tweetinvi.Streams.StreamTask.<RunStreamAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.StreamTask.<StartAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<StartAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<StartAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.FilteredStream.<StartMatchingAnyConditionAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TwitterApi.Program.<Main>d__0.MoveNext() in C:\Users\dkony\source\TwitterApi\Program.cs:line 97

**Comment by gem81** [comment]
Same problem. It's not tweeinvi problem
As far as I can see from the tcp connection logs, the break comes from the Twitter API side.

```
schannel: client wants to read 102400 bytes
schannel: encrypted data buffer: offset 0 length 103424
schannel: encrypted data got 31
schannel: encrypted data buffer: offset 31 length 103424
schannel: server closed the connection
schannel: schannel_recv cleanup
transfer closed with outstanding read data remaining
Closing connection 0
schannel: shutting down SSL/TLS connection with api twitter com port 443
schannel: clear security context handle
curl: (18) transfer closed with outstanding read data remaining
```
```
10:53:08.227497 IP 104.244.42.130.443 > xx.xx.54.10.46102: Flags [P.], seq 12099:12135, ack 1733, win 271, options [nop,nop,TS val 2093483055 ecr 1394112901], length 36
10:53:08.227586 IP xx.xx.54.10.46102 > 104.244.42.130.443: Flags [.], ack 12135, win 501, options [nop,nop,TS val 1394132912 ecr 2093483055], length 0

10:53:28.237228 IP 104.244.42.130.443 > xx.xx.54.10.46102: Flags [P.], seq 12135:12171, ack 1733, win 271, options [nop,nop,TS val 2093503064 ecr 1394132912], length 36
10:53:28.237302 IP xx.xx.54.10.46102 > 104.244.42.130.443: Flags [.], ack 12171, win 501, options [nop,nop,TS val 1394152922 ecr 2093503064], length 0

10:53:48.836734 IP 104.244.42.130.443 > xx.xx.54.10.46102: Flags [P.], seq 12171:12202, ack 1733, win 271, options [nop,nop,TS val 2093523664 ecr 1394152922], length 31
10:53:48.836734 IP 104.244.42.130.443 > xx.xx.54.10.46102: Flags [F.], seq 12202, ack 1733, win 271, options [nop,nop,TS val 2093523664 ecr 1394152922], length 0
```
after random time, anout 1-4 minutes server send TCP Fin packet and closing connection.

**Comment by dkonyayev** [comment]
I have wrapped the stream call in do/while loop. This works for me.

do
                {
                    try
                    {
                        await stream.StartMatchingAnyConditionAsync();
                    }
                    catch (Exception e)
                    {
                        _logger.LogError($"Error during stream: {e.Message}");
                    }
                } while (true);

**Comment by gem81** [comment]
yes, until you catch ~50 times "too many connections" with a few seconds
```
{"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}
```
, and after that "Rate limit exceeded"

```
< x-rate-limit-limit: 50
< x-rate-limit-reset: 1621027794
< x-content-type-options: nosniff
< x-rate-limit-remaining: 0
```

**Comment by gem81** [comment]
> My code: https://github.com/xPaw/TwitterToWebhook/blob/917f2541afdba93a6c22262b54bfa744df5d9ce1/TwitterToWebhook/TwitterStreaming.cs#L80
> 
> It worked on v4, I just changed it to use await/async.

Very bad idea use thread.sleep in async method 🤦🏻‍♂️Use await task.delay() instead of sleep(blocking thread)

**Comment by Scobiform** [comment]
You should also be able to catch it with.
EndOfStreamException

**Comment by gem81** [comment]
> You should also be able to catch it with.
> EndOfStreamException
> Then stop and restart the Stream.

No matter.  the problems started on 12.05.2021. I am catching all exceptions, but i can do nothing with “too many connections” at twi api after connection lost.

**Comment by waj520** [comment]
> I also experienced this today. I saw in the post previously that documentation will be updated about this but I did not find anything. Running version 5.0.4
> 
> System.IO.IOException
> HResult=0x80131620
> Message=The response ended prematurely.
> Source=Tweetinvi.Streams
> StackTrace:
> at Tweetinvi.Streams.StreamTask.d__25.MoveNext()
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Tweetinvi.Streams.StreamTask.d__24.MoveNext()
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Tweetinvi.Streams.Helpers.StreamResultGenerator.d__24.MoveNext()
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Tweetinvi.Streams.Helpers.StreamResultGenerator.d__23.MoveNext()
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Tweetinvi.Streams.FilteredStream.d__20.MoveNext()
> at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

Same, it is still there @linvi

**Comment by linvi** [comment]
Thanks for the info. I might find some time to look into this in 2 weeks from now.

**Comment by devjutsu** [comment]
Hey, any updates on this?
I have the same problem here with 5.0.4 :(
