### ISSUE TITLE
System.IO.IOException" in System.Private.CoreLib.dll ("The response ended prematurely.")

### ISSUE THREAD

**Issue by gem81** [linvi/tweetinvi#1125]
```
   at Tweetinvi.Streams.StreamTask.<RunStreamAsync>d__25.MoveNext() in D:\lua_src\TradeMiscTools\tweetinvi\Tweetinvi.Streams\StreamTask.cs:line 184
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.StreamTask.<StartAsync>d__24.MoveNext() in D:\lua_src\TradeMiscTools\tweetinvi\Tweetinvi.Streams\StreamTask.cs:line 121
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<StartAsync>d__24.MoveNext() in D:\lua_src\TradeMiscTools\tweetinvi\Tweetinvi.Streams\Helpers\StreamResultGenerator.cs:line 88
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.Helpers.StreamResultGenerator.<StartAsync>d__23.MoveNext() in D:\lua_src\TradeMiscTools\tweetinvi\Tweetinvi.Streams\Helpers\StreamResultGenerator.cs:line 61
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Tweetinvi.Streams.TweetStreamV2`1.<StartAsync>d__9.MoveNext() in D:\lua_src\TradeMiscTools\tweetinvi\Tweetinvi.Streams\V2\TweetStreamV2.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at TradeMiscTools.Core.TwitterServiceProvider.<RunFailoverServer2>d__10.MoveNext() in D:\lua_src\TradeMiscTools\TradeMiscTools\Core\TwitterServiceProvider.cs:line 98
```
<VersionPrefix>5.0.4</VersionPrefix>

Good afternoon.
How do I fix it?
This error pops up so often that the API eventually writes 'Rate Limit Exception'

**Comment by gem81** [comment]
Seems to be a twitter bug. closing issue
