### ISSUE TITLE
LatestDirectMessagesReceived has no setter

### ISSUE THREAD

**Issue by rquimby-instant-tech** [linvi/tweetinvi#159]
This is a problem I can't seem to find a solution for. I am trying to start two streams, one listening for DMs and the other listening for tweets that match a list of hashtags. The logs don't show that either stream starts, so I put break points at `_userStream.StartStream();` and `_filteredStream.StartSreamMatchingAllConditions();` but neither returns from execution when I step over those lines.

Any help is much appreciated.

This is my code:
```cs
public void Start()
{
    Log.Debug("starting twitter hub");
    ITwitterCredentials credentials = new TwitterCredentials(Consumer_Key, Consumer_Secret, Access_Token, Access_Token_Secret);
    Auth.SetCredentials(credentials);
    StartDMStream(credentials);
    StartHashTagStream(credentials);
}

private void StartDMStream(ITwitterCredentials credentials)
{
    try
    {
        _userStream = Stream.CreateUserStream(credentials);
        _userStream.MessageReceived += OnDmReceived;
        _userStream.StreamStopped += (sender, args) =>
        {
            _userStream.StartStream();
            Log.Debug("user stream listening for twitter messages received has re-started");
        };
         _userStream.StartStream();
        Log.Debug("user stream listening for twitter messages received has started");
    }
    catch (Exception ex)
    {
        Log.Error("Exception in " + ex.TargetSite.Name, ex);
    }
}

private void StartHashTagStream(ITwitterCredentials credentials)
{
    try
    {
        _filteredStream = Stream.CreateFilteredStream(credentials);
        foreach (string hashTag in HashTagsTrack)
        {
            _filteredStream.AddTrack(hashTag);
        }
        _filteredStream.FilterLevel = StreamFilterLevel.Medium;
        _filteredStream.MatchingTweetReceived += OnMatchingHashTagTweetReceived;
        _filteredStream.StreamStopped += (sender, args) =>
        {
            _filteredStream.StartStreamMatchingAllConditions();
            Log.Debug("filtered stream listening for matching hashtags has re-started");
        };
        _filteredStream.StartStreamMatchingAllConditions();
        Log.Debug("filtered stream listening for matching hashtags has started");
    }
    catch (Exception ex)
    {
        Log.Error("Exception in " + ex.TargetSite.Name, ex);
    }
}
```

**Comment by linvi** [comment]
`StartStream` is blocking (intentionally). Use `StartStreamAsync` if you want your UI thread to keep running.

**Comment by rquimby-instant-tech** [comment]
Thank you, that stopped it from blocking, however I'm still not receiving DM nor matching hashtag notifications. I added these lines to the `Start` method:
```cs
Log.Debug("starting twitter hub");
ITwitterCredentials credentials = new TwitterCredentials(Consumer_Key, Consumer_Secret, Access_Token, Access_Token_Secret);
Auth.SetCredentials(credentials);
var user = User.GetAuthenticatedUser();
var email = user.Email; //break point
```
When I inspect `user` object at the break point, I'm surprised that `LatestDirectMessagesReceived` is null despite there being several DMs sent to the authenticated user since yesterday.

Any ideas why that is?

**Comment by linvi** [comment]
Ok, something is obviously wrong with the `IAuthenticatedUser` interface.

`LatestDirectMessagesReceived ` is a field that is never filled by Tweetinvi. It is their so that the developers can set it. I will consider removing it, or adding the `setter` to the interface.

If you want the latest messages, either call `IAuthenticatedUser.GetLatestMessagesReceived` or `Message.GetLatestMessagesReceived`.

**Comment by rquimby-instant-tech** [comment]
> If you want the latest messages, either call IAuthenticatedUser.GetLatestMessagesReceived or Message.GetLatestMessagesReceived.

Both these return null. This account has recent DMs though, see below.


![twitterscreenshot](https://cloud.githubusercontent.com/assets/17907774/13853166/e190a452-ec3b-11e5-971a-73625dadce4f.png)

**Comment by linvi** [comment]
Please share your new code.

**Comment by rquimby-instant-tech** [comment]
```cs
            Log.Debug("starting twitter hub");
            ITwitterCredentials credentials = new TwitterCredentials(Consumer_Key, Consumer_Secret, Access_Token, Access_Token_Secret);
            Auth.SetCredentials(credentials);
            var user = User.GetAuthenticatedUser();
            var messages1 = user.GetLatestMessagesReceived();
            var messages2 = Message.GetLatestMessagesReceived();
            var message1 = messages1.FirstOrDefault();
            var message2 = messages2.FirstOrDefault();
```

messages1 and messages2 are null

**Comment by linvi** [comment]
Something wrong is happening in your code. could you check the error in the `ExceptionHandler`.
You can also consider disabling it.

https://github.com/linvi/tweetinvi/wiki/Exception-Handling#global-application-handling-mechanism

**Comment by rquimby-instant-tech** [comment]
Ok. 

New code:
```cs
 try
            {
                Log.Debug("starting twitter hub");
                ExceptionHandler.SwallowWebExceptions = false;
                ITwitterCredentials credentials = new TwitterCredentials(Consumer_Key, Consumer_Secret, Access_Token, Access_Token_Secret);
                Auth.SetCredentials(credentials);
                var user = User.GetAuthenticatedUser();
                var messages1 = user.GetLatestMessagesReceived(); //line 55 exception thrown here
...
```

Exception:
```
Tweetinvi.Core.Exceptions.TwitterException
message: https://api.twitter.com/1.1/direct_messages.json?count=40&include_entities=True&skip_status=False&full_text=true web request failed.
inner exception: null
stack trace:
   at Tweetinvi.Credentials.TwitterAccessor.HandleQueryException(TwitterException ex)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Messages.MessageQueryExecutor.GetLatestMessagesReceived(Int32 maximumMessages)
   at Tweetinvi.Controllers.Messages.MessageController.GetLatestMessagesReceived(Int32 maximumMessages)
   at Tweetinvi.Logic.AuthenticatedUser.<>c__DisplayClass73_0.<GetLatestMessagesReceived>b__0()
   at Tweetinvi.Logic.AuthenticatedUser.ExecuteAuthenticatedUserOperation[T](Func`1 operation)
   at Tweetinvi.Logic.AuthenticatedUser.GetLatestMessagesReceived(Int32 maximumNumberOfMessagesToRetrieve)
   at MySolution.MyNamespace.MyClass.Start() in d:\MyFolder1\MyFolder2\MySolution\MyNamespace\MyClass.cs:line 55


```

**Comment by linvi** [comment]
Thank you but I need the exception details of the TwitterException.
Please `catch (TwitterException ex)` and post here `ex.ToString()`

**Comment by rquimby-instant-tech** [comment]
ex.ToString():
```
--- Date : 3/17/2016 2:47:39 PM
URL : https://api.twitter.com/1.1/direct_messages.json?count=40&include_entities=True&skip_status=False&full_text=true
Code : 403
Error documentation description : Forbidden - The request is understood, but it has been refused or access is not allowed. An accompanying error message will explain why. This code is used when requests are being denied due to update limits.
Error message : https://api.twitter.com/1.1/direct_messages.json?count=40&include_entities=True&skip_status=False&full_text=true web request failed.
This application is not allowed to access or delete your direct messages. (93)
```

This last message makes me think I set up my connected App wrong.

**Comment by linvi** [comment]
> This application is not allowed to access or delete your direct messages. (93)

It means that on apps.twitter.com you did not give the rights to access the Direct Messages.

In the `Permission` tab you need to specify `Read, Write and Access direct messages`.

**Comment by rquimby-instant-tech** [comment]
Excellent, thank you so much for your prompt help and attention!! I have received the notification that a DM had occurred and for the hashtags I'm watching! Thank you again!

**Comment by linvi** [comment]
I reopen for the `LatestDirectMessagesReceived` that needs to be fixed.
