### ISSUE TITLE
Frequent "Object reference not set to an instance of an object" Exceptions on ASP.NET server.

### ISSUE THREAD

**Issue by AlanReckInContextSolutions** [linvi/tweetinvi#324]
I start up a stream tracking a single hashtag, nothing fancy.  Tweets will be caught, and all seems well, but fairly frequently my ASP.NET server will crash with a null reference exception, with the following callstack:

   at System.Runtime.CompilerServices.AsyncServices.<ThrowAsync>b__1(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

I have narrowed this down to TweetInvi by disabling the feature for a while, and I just turned it back on tonight and the error is back.  Also, we don't personally run any worker threads in this particular application.

Unfortunately the anonymous method makes things harder to decipher :-(.

Any assistance?  We really would like to have a solution pronto!

**Comment by linvi** [comment]
I will need to see your code to help you.

**Comment by linvi** [comment]
Closing the issue because no code provided.
