### ISSUE TITLE
Streams only return maximum one tweet for Windows Phone 8.1

### ISSUE THREAD

**Issue by patrikohlsson** [linvi/tweetinvi#51]
I'm using Visual Studio Express 2013 on a Windows 10 machine.

To replicate:
Create an default WP8.1 app or a Universal app.
Add Tweetinvi to WP project using NuGet package manager.
Add this code:
```c#
Auth.SetUserCredentials("", "", "", "");
var fs = Tweetinvi.Stream.CreateSampleStream();
fs.TweetReceived += 
    (sender, args) =>
    {
        Debug.WriteLine("Tweet Received");
    };
fs.StartStream();
```

This only returns 0-1 tweets and after a few minutes the StreamStopped callback is called with the exception:
```
Autofac.Core.DependencyResolutionException: None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Tweetinvi.Logic.TwitterQuery' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.String queryURL' of constructor 'Void .ctor(System.String, Tweetinvi.Core.Enum.HttpMethod)'.
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve(IComponentContext context, Type serviceType, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Tweetinvi.Injectinvi.AutofacThreadContainer.Resolve[T](IConstructorNamedParameter[] parameters)
   at Tweetinvi.Injectinvi.AutofacContainer.Resolve[T](IConstructorNamedParameter[] parameters)
   at Tweetinvi.Core.Injectinvi.Factory`1.Create(IConstructorNamedParameter[] parameters)
   at Tweetinvi.Streams.StreamTask.GetJsonResponseFromReader()
   at Tweetinvi.Streams.StreamTask.Start()
```

The exact same code works fine in ordinary Windows 8.1 apps. I haven't tried yet with VS 2015.
Might be related to: 
https://tweetinvi.codeplex.com/workitem/2619

**Comment by patrikohlsson** [comment]
Made a Windows 10 Universal app now in VS 2015 and streams work on the phone emulator. Probabiy a WP version 8 / 8.1 issue only.

**Comment by linvi** [comment]
Thank you for the feedback. 

Would you please try the version 0.9.10.0 available through the Source Code and let me know if you encounter the same issue.

I will try to test this on Windows Phone as soon as I can.

**Comment by patrikohlsson** [comment]
Sorry, none of the projects open in VS Express 2015 (it's only for building universal apps), I'll install Community this weekend. Have verified now that streams work even on an actual Windows Mobile 10 device and not only the emulator but I'm having some other random issues, but I'll post them separately.

**Comment by linvi** [comment]
Should I consider this issue as fixed, I am not sure I understand what is the current state of this problem.

Let me know if you need more help.

**Comment by patrikohlsson** [comment]
The issue still exists but it is likely limited to WP 8.1 and the phone part of universal apps made in VS 2013.
It would be good to get confirmation. If you've got VS 2013, could you try starting a stream (any kind) on the emulator? It doesn't work for me in the emulator or on a real device but I have only one computer atm to try on and I've tried everything :)

**Comment by linvi** [comment]
I will work on this tomorrow and keep you up to date.

**Comment by linvi** [comment]
Just to let you know, I am able to reproduce the issue.

**Comment by linvi** [comment]
Some news concerning this bug. It looks like `HttpClient` (Windows.Web.Http.HttpClient) has a specific implementation for Windows Phone which is not compatible with Portable Class Libraries as the `Microsoft.Net.Http`.

Using the PCL HttpClient, the .Async seems to block. I have verified with other libraries in .NET and they act the same way.

I am not sure how I will fix this issue yet, I might have to create an additional .dll and tweak the initialization of the library.

In the meantime I won't leave this issue block the release of version 0.9.10.0 as it brings various fixes and improvements but I will work on it for the release 0.9.10.1.

**Comment by linvi** [comment]
After various investigation it looks like infinite stream support for Windows Phone 8.1 with Portable Class Libraries does not work as expected. As I want to keep the library Portable I will not fix this issue.

If you need, you can fix the issue simply by changing the `System.Net.Http.HttpClient` in `Windows.Web.Http.HttpClient` in the class `Tweetinvi.WebLogic.HttpClientWebHelper` located in *Tweetinvi.WebLogic > HttpClientWebHelper.cs*.

Thank you for your understanding and sorry for this non-fix.
