### ISSUE TITLE
Cannot seem to authenticate

### ISSUE THREAD

**Issue by Metabie** [linvi/tweetinvi#516]
As soon as I authenticate I get a System.AggregateException:

```
System.AggregateException occurred
  HResult=0x80131500
  Message=Mindestens ein Fehler ist aufgetreten.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass4_0.<ExecuteQuery>b__0() in ...\Tweetinvi.WebLogic\WebRequestExecutor.cs:line 71
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafely[T](ITwitterQuery twitterQuery, Func`1 action) in ...\Tweetinvi.WebLogic\WebRequestExecutor.cs:line 167
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteQuery(ITwitterQuery twitterQuery, ITwitterClientHandler handler) in ...\Tweetinvi.WebLogic\WebRequestExecutor.cs:line 39
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent) in ...\Tweetinvi.WebLogic\TwitterRequestHandler.cs:line 87
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow) in ...\Tweetinvi.Credentials\TwitterAccessor.cs:line 388
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method) in ...\Tweetinvi.Credentials\TwitterAccessor.cs:line 360
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters) in ...\Tweetinvi.Credentials\TwitterAccessor.cs:line 126
   at Tweetinvi.Factories.User.UserFactoryQueryExecutor.GetAuthenticatedUser(IGetAuthenticatedUserParameters parameters) in ...\Tweetinvi.Factories\User\UserFactoryQueryExecutor.cs:line 44
   at Tweetinvi.Factories.User.UserFactory.GetAuthenticatedUser(ITwitterCredentials credentials, IGetAuthenticatedUserParameters parameters) in ...\Tweetinvi.Factories\User\UserFactory.cs:line 43
   at Tweetinvi.User.GetAuthenticatedUser(ITwitterCredentials credentials, IGetAuthenticatedUserParameters parameters) in ...\Tweetinvi\User.cs:line 92
   at TwitterTest.Form1..ctor() in ...\TwitterTest\Form1.cs:line 33
   at TwitterTest.Program.Main() in ...\TwitterTest\Program.cs:line 19

Inner Exception 1:
MissingMethodException: Methode nicht gefunden: "Void System.Net.Http.HttpClientHandler.set_Proxy(System.Net.IWebProxy)".

Line 33 = var authenticatedUser = User.GetAuthenticatedUser();

Line before that:

Auth.SetUserCredentials(ConsumerKey, ConsumerSecret, AccessToken, TokenSecret);
```

And the keys are correct

Thank you in advance,

**Comment by linvi** [comment]
Which version of the library are you using?
