### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by kalidorweb** [linvi/tweetinvi#539]
Great library but unfortunately throws an exception (tweetinvi was installed with NuGet):
ExceptionHandler.SwallowWebExceptions = false and
ExceptionHandler.GetLastException()
don't work. Code: 
``` c#
var credentialsAccessor = TweetinviContainer.Resolve<ICredentialsAccessor>();
Auth.SetUserCredentials("njrndtmCP6ZwOUrwe1111111",
						"4QUJjMzPzRjR5M1rvX2TP4nYirGHmCUoQ8Arg2gPNixAV6666",
						"775790736889507840-ZITMsooQjPk3tetwPVRxPDnCtIf7ee",
						"pBMOjt21JyrNMWWiV7V6T81eGANjUwJc1weQPAC1Alrew");
var stream = Stream.CreateFilteredStream();
stream.AddTweetLanguageFilter(LanguageFilter.English);
stream.AddTrack("internet");
stream.AddTrack("search");
stream.MatchingTweetReceived += (sender, args) =>
							 {
								  var tweet = args.Tweet;
								  Console.WriteLine(tweet.Text);
							 };
stream.StreamStarted += (sender, args) => Console.WriteLine("stream started\r\n");
stream.AddTrack("some keyword");
stream.AddTrack("another keyword");

stream.NonMatchingTweetReceived += (sender, args) => Console.WriteLine("nonMatching tweet");
stream.DisconnectMessageReceived += (sender, args) => Console.WriteLine("disconnected message");
stream.LimitReached += (sender, args) => Console.WriteLine("limit reached: not received tweets" + args.NumberOfTweetsNotReceived);
stream.JsonObjectReceived += (sender, args) => Console.WriteLine("JsonObjectReceived");
stream.WarningFallingBehindDetected += (sender, args) => Console.WriteLine("falling behind...");
stream.StreamPaused += (sender, args) => Console.WriteLine("stream paused");
stream.StreamResumed += (sender, args) => Console.WriteLine("stream resumed");
stream.StreamStopped += (sender, args) => Console.WriteLine("stream stoped: " + args.DisconnectMessage.Reason);
stream.TweetDeleted += (sender, args) => Console.WriteLine("tweet deleted");
stream.UnmanagedEventReceived += (sender, args) => Console.WriteLine("unmanaged event");
stream.UserWitheld += (sender, args) => Console.WriteLine("user withheld");
stream.StartStreamMatchingAllConditions();
Console.ReadLine();
```
output: 
stream started
stream resumed

``` c#
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Tweetinvi.Core.Exceptions.SingleAggregateExceptionThrower.ExecuteActionAndThrowJustOneExceptionIfExist(Action action)
   at ConsoleTweetBot.Program.Main(String[] args_) in c:\Projects\ConsoleTweetBot\Program.cs:line 55
```

**Comment by linvi** [comment]
Hello,

Thank you for reporting this issue.
Could you share your project file so that I can see what is the line 55.

Cheers,
Linvi

**Comment by linvi** [comment]
No feedback => closing
