### ISSUE TITLE
Upload.UploadImage exception

### ISSUE THREAD

**Issue by leventeolahx** [linvi/tweetinvi#540]
Hi Linvi,

Sometimes we are getting an exception when Upload.UploadImage or Upload.UploadVideo is called.
Below you can find details about the exception.

Cheers,
Levente

> System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Tweetinvi.WebLogic.HttpClientWebHelper.<GetHttpResponse>d__0.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass5_0.<ExecuteMultipartQuery>b__0()
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafely[T](ITwitterQuery twitterQuery, Func`1 action)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteMultipartQuery(IMultipartHttpRequestParameters parameters)
   at Tweetinvi.Credentials.TwitterAccessor.TryExecuteMultipartQuery(IMultipartHttpRequestParameters parameters, String& result)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteMultipartQuery[T](IMultipartHttpRequestParameters parameters, JsonConverter[] converters)
   at Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadMedias(IEnumerable`1 medias, Boolean forceReUpload)
   at Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadBinaries(IEnumerable`1 binaries)
   at Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadBinary(Byte[] binary)
   at C3.Core.Services.Twitter.TwitterService.<>c__DisplayClass19_0.<PostToProfile>b__0() in C:\...
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.BeginWrite(Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   --- End of inner exception stack trace ---
   at System.Net.ConnectStream.EndWrite(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Tweetinvi.WebLogic.HttpClientWebHelper.<GetHttpResponse>d__0.MoveNext()<---

**Comment by kalidorweb** [comment]
Do you have project for visual studio 2013? Where can I get it?

Yours Truly,
Oleg Leonov,
Serbia

**Comment by kalidorweb** [comment]
I mean your old project for vs2013.

Oleg

**Comment by leventeolahx** [comment]
No, we are using tweetinvi from nugdet in visual studio 2015.

Levente

**Comment by linvi** [comment]
Hello here!

I am not sure what the error is but it certainly looks like a problem with the Twitter API.
Is the problem still occurring?

Cheers,
Linvi

**Comment by linvi** [comment]
Closing until I have more information.

Please feel free to reopen.
