### ISSUE TITLE
Received an unexpected EOF or 0 bytes from the transport stream.

### ISSUE THREAD

**Issue by rotem156** [linvi/tweetinvi#70]
The filtered stream was open for couple of hours and then this exception hit me, keep in mind that i'm using MessageBox.Show() to get notified of these exceptions.

Edit: Here's a stacktrace.

Start DateTime: 
24/10/2015 18:39:30

Exception DateTime: 
25/10/2015 01:45:41

Message: 
Received an unexpected EOF or 0 bytes from the transport stream.

Call Stack:    
at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at AsyncExtensions.<>c__DisplayClassf.<ReadLineAsync>b__e()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by linvi** [comment]
This issue can also happen. This usually happens when the event `MatchingTweet` received is not handled quickly enough. As Tweetinvi is a library, I do not want to keep the objects in memory, therefore I wait for the event to be finished in order to continue and the reading of the `Stream`. A stream not being read for a certain amount of time can result in the `Stream` to be stopped.

Please note that this can also happen based on the connection and other external factors, as for the StreamStopped issue, please listen to the `StreamStopped` event and restart the `Stream`.
