### ISSUE TITLE
Queries involving RateLimitTracker appear to be failing

### ISSUE THREAD

**Issue by chriswill** [linvi/tweetinvi#713]
I've had these queries running successfully for months, but they appear to have take a turn south over the last day or so.  Queries involving RateLimitTracking throw an error of "Exception has been thrown by the target of an invocation".

I set up my Twitter service with a simple call like this:
```
RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
            RateLimit.ClearRateLimitCache();

            TwitterCredentials twitterCredentials = new TwitterCredentials(TwitterConfiguration.ConsumerKey, TwitterConfiguration.ConsumerSecret, 
                twitterApplicationCredential.Token, twitterApplicationCredential.TokenSecret);
            Auth.SetCredentials(twitterCredentials);
```

and then make a call to get user by ID.

This fails, returning an error of "Exception has been thrown by the target of an invocation." and a stack trace like this:

```   
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Tweetinvi.Credentials.RateLimit.RateLimitHelper.GetEndpointRateLimitFromQuery(String query, ICredentialsRateLimits rateLimits, Boolean createIfNotExist)
   at Tweetinvi.Credentials.RateLimit.RateLimitCacheManager.GetQueryRateLimit(String query, ITwitterCredentials credentials)
   at Tweetinvi.WebLogic.TwitterRequestHandler.TryPrepareRequest(IHttpRequestParameters requestParameters, RateLimitTrackerMode rateLimitTrackerMode, ITwitterCredentials credentials, Boolean raiseEvents, ITwitterQuery& twitterQuery)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Factories.User.UserFactoryQueryExecutor.GetUserDTOFromId(Int64 userId)
   at Tweetinvi.Factories.User.UserFactory.GetUserFromId(Int64 userId)
   at CloudScope.Social.Services.Twitter.TwitterService.GetUser(Int64 accountId) in D:\src\CloudScope.Social\CloudScope.Social.Services\Twitter\TwitterService.cs:line 146
   at CloudScope.Social.Agent.Tasks.AccountTask.<RunTaskAsync>d__3.MoveNext() in D:\src\CloudScope.Social\CloudScope.Social.Agent\Tasks\AccountTask.cs:line 111
```

when I switch the RateLimitTrackerMode to RateLimitTrackerMode.None, the call completes successfully.

**Comment by anjana-sharma** [comment]
Same here, i am using tweetinvi from last three months, My code was working fine but now it is throwing exception when my code is going to track Rate Limit on following line.
 RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackOnly;
var rateLimits = RateLimit.GetCurrentCredentialsRateLimits();
![ratelimits](https://user-images.githubusercontent.com/19988665/40763736-611aef2c-64bf-11e8-8a98-11d25d21e5e5.png)

ERROR:
Exception has been thrown by the target of an invocation
@linvi please look into this.
Kind Regards

**Comment by chriswill** [comment]
I duplicated this by modifying the Examplinvi.NETStandard sample to look like this:

'''
RateLimit.RateLimitTrackerMode = RateLimitTrackerMode.TrackAndAwait;
            var authenticatedUser = User.GetAuthenticatedUser();

            Console.WriteLine(authenticatedUser);
'''

In CredentialsRateLimits.cs, line 45, every property on _resources is null, including AccountRateLimits.

**Comment by linvi** [comment]
Thank you for reporting it. I will be having a look tonight.

**Comment by FurkanGozukara** [comment]
same problem

i was going mad since yesterday to solve this problem :/

**Comment by linvi** [comment]
Hi,

The Twitter API is now returning the credentials once again.
Though, I will make Tweetinvi more robust and flexible in case this was to happen again.

As Twitter is back on, I consider that this issue does not require a "rushed" fix and I will issue it as part of Tweetinvi 6.0.

Thank you for your understanding.
If you do encounter this issue once again, I will prioritize this task.

Cheers,
Linvi

**NOTES FOR FUTURE FIX :**

Json received from `https://api.twitter.com/1.1/application/rate_limit_status.json`

``` json
{
  "rate_limit_context": {
    "access_token": "___"
  },
  "resources": {  }
}
```
