### ISSUE TITLE
Autofac throws Exception

### ISSUE THREAD

**Issue by user156** [linvi/tweetinvi#74]
http://i.imgur.com/ZlOVfcU.png

Start DateTime: 
26/10/2015 16:57:19

Exception DateTime: 
28/10/2015 21:31:02

Message: 
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Tweetinvi.Logic.TwitterQuery' can be invoked with the available services and parameters:
Cannot resolve parameter 'System.String queryURL' of constructor 'Void .ctor(System.String, Tweetinvi.Core.Enum.HttpMethod)'.

Call Stack:    
at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Activators.Reflection.AutowiringParameter.<>c__DisplayClass2.<CanSupplyValue>b__0()
   at Autofac.Core.Activators.Reflection.ConstructorParameterBinding.Instantiate()
   at Autofac.Core.Activators.Reflection.ReflectionActivator.ActivateInstance(IComponentContext context, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Activate(IEnumerable`1 parameters)
   at Autofac.Core.Resolving.InstanceLookup.Execute()
   at Autofac.Core.Resolving.ResolveOperation.GetOrCreateInstance(ISharingLifetimeScope currentOperationScope, IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Resolving.ResolveOperation.Execute(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.Core.Lifetime.LifetimeScope.ResolveComponent(IComponentRegistration registration, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.TryResolveService(IComponentContext context, Service service, IEnumerable`1 parameters, Object& instance)
   at Autofac.ResolutionExtensions.ResolveService(IComponentContext context, Service service, IEnumerable`1 parameters)
   at Autofac.ResolutionExtensions.Resolve[TService](IComponentContext context, IEnumerable`1 parameters)
   at Tweetinvi.Injectinvi.AutofacThreadContainer.Resolve[T](IConstructorNamedParameter[] parameters)
   at Tweetinvi.Injectinvi.AutofacContainer.Resolve[T](IConstructorNamedParameter[] parameters)
   at Tweetinvi.Core.Injectinvi.Factory`1.Create(IConstructorNamedParameter[] parameters)
   at Tweetinvi.Streams.StreamTask.GetJsonResponseFromReader(StreamReader reader, ITwitterQuery twitterQuery)
   at Tweetinvi.Streams.StreamTask.Start()

**Comment by linvi** [comment]
Please share your code so that I can help you. I specially need to know which type of stream you are trying to use.

**Comment by rotem156** [comment]
Filtered Stream, go on skype and i will send you the project source code.

**Comment by linvi** [comment]
None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Tweetinvi.Logic.TwitterQuery' can be invoked with the available services and parameters: Cannot resolve parameter 'System.String queryURL' of constructor 'Void .ctor(System.String, Tweetinvi.Core.Enum.HttpMethod)'.

**Comment by linvi** [comment]
Fixed by https://github.com/linvi/tweetinvi/commit/ab75e6169fe936d2cb3bb460ffab4ce6621627d7
