### ISSUE TITLE
Unable to read data from the transport connection: ‏‏Operation Aborted By A Call To - WSACancelBlockingCall‏.

### ISSUE THREAD

**Issue by user156** [linvi/tweetinvi#77]
Start DateTime: 
01/11/2015 19:32:37

Exception DateTime: 
01/11/2015 20:23:05

Exception.Message: 
Unable to read data from the transport connection: Operation Aborted By A Call To - WSACancelBlockingCall‏.

Exception.StackTrace:    
at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.Http.HttpClientHandler.WebExceptionWrapperStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.DelegatingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
   at AsyncExtensions.<>c__DisplayClassf.<ReadLineAsync>b__e()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

InnerException.Message: 
Operation Aborted By A Call To - WSACancelBlockingCall‏.

**Comment by linvi** [comment]
Hi there,

This is probably a bug directly within your application. It looks like one of your thread is blocking/closing the Stream.

I know you tried to send some code to me by skype but I have not received it.

Cheers,
Linvi

**Comment by rotem156** [comment]
Well, how could i send you the source if you never go on skype ?

**Comment by linvi** [comment]
This issue has been solved and was not a Tweetinvi issue.
