### ISSUE TITLE
A task was canceled.

### ISSUE THREAD

**Issue by rdahan156** [linvi/tweetinvi#87]
Start DateTime: 
19/11/2015 14:46:07

Exception DateTime: 
19/11/2015 14:46:41

Exception.Message: 
A task was canceled.

Exception.StackTrace:   
 at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Tweetinvi.Streams.StreamTask.<GetStreamReader>d__28.MoveNext()

linvi, check this out:
http://stackoverflow.com/questions/15181855/why-does-taskcanceledexception-occur
http://stackoverflow.com/questions/19120675/httpclient-task-was-cancelled-how-to-get-the-exact-error-message

**Comment by linvi** [comment]
Have you received this error multiple times?

**Comment by user156** [comment]
Yes, i get this a lot.

**Comment by linvi** [comment]
I think this issue mostly happens when the Timeout is reached, which is not an issue.
I don't think this is a problem but more issues with the connection and the WebRequest, not something that I could fix.

**Comment by kalidorweb** [comment]
Great lib, but StartStreamMatchingAnyCondition doesn't work.
