### ISSUE TITLE
Trying to Create a Tweet with Tweetinvi 0.9.10, but not able to send. 

### ISSUE THREAD

**Issue by skvnoida** [linvi/tweetinvi#92]
![capture](https://cloud.githubusercontent.com/assets/16157079/11598902/74c106a2-9aea-11e5-8201-49e21a5447eb.PNG)
Trying to Create a Tweet with Tweetinvi 0.9.10, but not able to send. 

C# Code

            Thread.CurrentThread.CurrentCulture = new CultureInfo("en-US");
            Thread.CurrentThread.CurrentUICulture = new CultureInfo("en-US");

            TwitterCredentials userCredentials = new TwitterCredentials(Access_Token, Access_Token_Secret, Consumer_Key, Consumer_Secret);
            Auth.SetCredentials(userCredentials);
            ExceptionHandler.SwallowWebExceptions = false;
            try
            {
                var tweet = Tweet.PublishTweet("I'm back! Deal with devil.");
            }
            catch (Exception ex)
            {
                string s = ex.Message;
            }

Error
((Tweetinvi.Core.Exceptions.TwitterException)ex).TwitterDescription
Unauthorized -  Authentication credentials were missing or incorrect.
ex.Message
https://api.twitter.com/1.1/statuses/update.json?status=I%27m%20back%21%20Deal%20with%20devil. web request failed.
ex.StackTrace
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method)
   at Tweetinvi.Credentials.TwitterAccessor.ExecutePOSTQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Controllers.Tweet.TweetQueryExecutor.PublishTweet(IPublishTweetParameters publishParameters)
   at Tweetinvi.Controllers.Tweet.TweetController.InternalPublishTweet(IPublishTweetParameters parameters)
   at Tweetinvi.Controllers.Tweet.TweetController.PublishTweet(String text, IPublishTweetOptionalParameters optionalParameters)
   at Tweetinvi.Tweet.PublishTweet(String text, IPublishTweetOptionalParameters publishTweetOptionalParameters)
   at Automation.Form1.button3_Click(Object sender, EventArgs e) in

**Comment by skvnoida** [comment]
Make it work, The DLLs from NuGet is throwing execption. However, codepelx dlls work fine.
