### ISSUE TITLE
Library inconsistently throws a System.NullReferenceException when using Upload.UploadVideo

### ISSUE THREAD

**Issue by GodsWithin** [linvi/tweetinvi#922]
Recently I've wanted to use the library to attatch videos to a tweet.
I tried passing the video as a byte array to the `MediaBinairies ` property of `PublishTweetOptionalParameters`, but that threw an exception saying that there was an issue with the provided binary. So I looked again at the wiki which states that you should use the static `Upload` class to upload video files to Twitter, so following the wiki I used this bit of code to perform the upload. The exception is thrown on the first line when it tries to upload the video.

```cs
tempMedia = Upload.UploadVideo(bytes);
Upload.WaitForMediaToBecomeAvailable(tempMedia);
```

Full stacktrace:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Tweetinvi.Controllers.Upload.UploadHelper.WaitForMediaProcessingToGetAllMetadata(IMedia media) in C:\Users\linvi\dev\tweetinvi\Tweetinvi.Controllers\Upload\UploadHelper.cs:line 52
   at Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadBinary(IUploadParameters uploadQueryParameters) in C:\Users\linvi\dev\tweetinvi\Tweetinvi.Controllers\Upload\UploadQueryExecutor.cs:line 121
   at Shine.Services.TwitterService.PublishInstagramUpdateTweet(List`1 descriptions, List`1 media) in C:\Users\robin\source\repos\Shine\Shine\Services\TwitterService.cs:line 279
   at Tweetinvi.Controllers.Upload.UploadHelper.WaitForMediaProcessingToGetAllMetadata(IMedia media) in C:\Users\linvi\dev\tweetinvi\Tweetinvi.Controllers\Upload\UploadHelper.cs:line 52
   at Tweetinvi.Controllers.Upload.UploadQueryExecutor.UploadBinary(IUploadParameters uploadQueryParameters) in C:\Users\linvi\dev\tweetinvi\Tweetinvi.Controllers\Upload\UploadQueryExecutor.cs:line 121
   at Shine.Services.TwitterService.PublishInstagramUpdateTweet(List`1 descriptions, List`1 media) in C:\Users\user\source\repos\Shine\Shine\Services\TwitterService.cs:line 279 // my project
```

This exception is not thrown 100% of the time, I've reran the code several times, sometimes the upload succeeds, sometimes this exception is thrown, so I'm not sure what is causing this.

If you need more information, do let me know and I'll try to respond asap.

**Comment by linvi** [comment]
Thank you for reporting the issue. I will try to have a look at it within 5 days.

**Comment by GodsWithin** [comment]
@linvi 
For what it's worth, I've pushed that piece of code to my production, but with exception handling added in the case this were to happen again.  In the (very limitted) half a dozen times that code has been executed, the exception did not occur again.
