### ISSUE TITLE
Tweetinvi.User.GetAuthenticatedUser() Throws Exceptions | .Net Core 3.0

### ISSUE THREAD

**Issue by daz1761** [linvi/tweetinvi#934]
I'm trying to get this working at a very basic level where you print the name of the user account via a console app:
```
namespace TwitterInviTest
{
    class Program
    {
        static void Main(string[] args)
        {
            string conKey = "xxxx";
            string conSecret = "xxxx";
            string accessToken = "1652425256-xxxx";
            string accessTokenSecret = "xxxx";

            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls
                                                   | SecurityProtocolType.Tls11
                                                   | SecurityProtocolType.Tls12
                                                   | SecurityProtocolType.Tls13;

            ExceptionHandler.SwallowWebExceptions = false;
            
            Auth.SetUserCredentials(conKey, conSecret, accessToken, accessTokenSecret);
            var user = User.GetAuthenticatedUser();
            
            Console.WriteLine(user);
        }
    }
}
```
The `ServicePointManager.SecurityProtocol` was added after reading about similar problems, but doesn't help in my case.

Here are the exceptions:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.)
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
   at System.Net.Security.SslStream.ThrowIfExceptional()
   at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Tweetinvi.WebLogic.HttpClientWebHelper.GetHttpResponse(ITwitterQuery twitterQuery, ITwitterClientHandler handler)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Tweetinvi.WebLogic.WebRequestExecutor.<>c__DisplayClass4_0.<ExecuteQuery>b__0()
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteTwitterQuerySafely[T](ITwitterQuery twitterQuery, Func`1 action)
   at Tweetinvi.WebLogic.WebRequestExecutor.ExecuteQuery(ITwitterQuery twitterQuery, ITwitterClientHandler handler)
   at Tweetinvi.WebLogic.TwitterRequestHandler.ExecuteQuery(String queryURL, HttpMethod httpMethod, TwitterClientHandler handler, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQuery(String query, HttpMethod method, ITwitterCredentials credentials, HttpContent httpContent)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteQueryReturningContent(String query, HttpMethod method, HttpContent httpContent, Boolean forceThrow)
   at Tweetinvi.Credentials.TwitterAccessor.ExecuteGETQuery[T](String query, JsonConverter[] converters)
   at Tweetinvi.Factories.User.UserFactoryQueryExecutor.GetAuthenticatedUser(IGetAuthenticatedUserParameters parameters)
   at Tweetinvi.Factories.User.UserFactory.GetAuthenticatedUser(ITwitterCredentials credentials, IGetAuthenticatedUserParameters parameters)
   at Tweetinvi.User.GetAuthenticatedUser(ITwitterCredentials credentials, IGetAuthenticatedUserParameters parameters)
   at TwitterInviTest.Program.Main(String[] args) in /home/daz/dev/Test/TwitterInviTest/Program.cs:line 24
```

**Comment by daz1761** [comment]
Apologies for closing and reopening but it seems to be intermittent.

**Comment by daz1761** [comment]
Finally closing as it appears to be my works network that is blocking the api during working hours!
